### ISSUE TITLE
Seem Something wrong with gtp connection

### ISSUE THREAD

**Issue by startnoob** [popojan/goban#11]
I set the engine as leelazero and ran the executable file, it crashed.
this is the log file:

> [2018-12-14 18:21:37.099] [console] [info] TODO log using spdlog!
DISPLAY 0x5618710a0af0
DISPLAY << 0x5618710a0af0
Loaded font face Lacuna Regular Regular (from byte stream).
Loaded font face Lacuna Italic Regular (from byte stream).
preSetContext = 0
preLoadFonts = 0
Loaded font face Delicious Roman (from data/gui/Delicious-Roman.otf).
Loaded font face Delicious Italic (from data/gui/Delicious-Italic.otf).
Loaded font face Delicious Bold (from data/gui/Delicious-Bold.otf).
Loaded font face Delicious Bold Italic (from data/gui/Delicious-BoldItalic.otf).
preLoadWindow = 0
preOverlayCreate = 0
Enter: demo_glstate_create
Enter: demo_shader_create_program
Enter: compile_shader
Leave: compile_shader
Enter: compile_shader
Leave: compile_shader
Enter: link_program
Leave: link_program
Leave: demo_shader_create_program
Enter: demo_atlas_create
Leave: demo_atlas_create
Leave: demo_glstate_create
Setting debug to 0
Setting contrast to 1
Setting gamma_adjust to 1
Setting outline to 0
Setting outline_thickness to 0
Setting boldness to 0
Setting depth to 0
 10 glyphs; avg num endpoints 34.20; avg error 58.5%; avg tex fetch 3.15; avg  2.46kb per glyph
preShaderInit = 0
[2018-12-14 18:21:37.190] [console] [info] preShaderInitProgram = 0
[2018-12-14 18:21:37.198] [console] [info] postShaderGetProgram = 0
[2018-12-14 18:21:37.198] [console] [info] postShaderUniformsLocations = 0
postShaderOverlayInits = 0
postInitTranslation = 0
[2018-12-14 18:21:37.198] [console] [info] leelaz
[2018-12-14 18:21:37.198] [console] [info] leelaz -g -t 2 -w ./network.gz --noponder
""
[2018-12-14 18:21:37.199] [console] [info] running child
0newType = [human = 0, computer = 1] newRole = [black = 0, white = 0]
Before parsing SGF
Parsed SGF
1
postPreconstructElement = 0
[2018-12-14 18:21:37.225] [console] [info] sendline = [boardsize 19]
[2018-12-14 18:21:37.225] [console] [info] get line
[2018-12-14 18:21:45.373] [console] [info] getline = [=]
[2018-12-14 18:21:45.373] [console] [info] getline = []
setting komi 6.5
[2018-12-14 18:21:45.373] [console] [info] sendline = [komi 6.5]
[2018-12-14 18:21:45.373] [console] [info] get line
[2018-12-14 18:21:45.373] [console] [info] getline = [=]
[2018-12-14 18:21:45.373] [console] [info] getline = []

this is the config settings:

> ./leelaz
leelaz
leelaz -g --quiet -t 2 -w ./network.gz --noponder
leela_zero
0

then it crashed.
Hundreds of thanks!

**Comment by popojan** [comment]
The new win10-x64 builds use boost.process integrated in boost, so the syntax of third line in config settings slightly changed and should contain only engine command line parameters. Please try this config:

> ./leelaz
> leelaz
> -g --quiet -t 2 -w ./network.gz --noponder
> leela_zero
> 0

Given your config I assume you have got such folder structure:
> ./leelaz/leelaz.exe
> ./network.gz

**Comment by startnoob** [comment]
Sorry, My operating system is Ubuntu.

**Comment by popojan** [comment]
Ah, sorry, are you running in wine or have you compiled from source?
Yet, the note about third line syntax is still valid.

**Comment by startnoob** [comment]
I compiled the source code.
Here is the flie structure:

> .
.
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   ├── cmake_install.cmake
│   ├── goban
│   └── Makefile
├── cmake
│   ├── FileList.cmake
│   ├── FindGnuGo.cmake
│   ├── FindLibGlyphy.cmake
│   ├── FindLibRocket.cmake
│   ├── FindLibSndFile.cmake
│   └── FindPortaudio.cmake
├── CMakeLists.txt
├── config
│   ├── engines.available
│   └── engines.enabled
├── data
│   ├── glsl
│   ├── gui
│   └── sound
├── deps
│   ├── glyphy
│   ├── libRocket
│   ├── make.bat
│   ├── Makefile
│   ├── _patches
│   └── spdlog
├── goban
├── INSTALL.md
├── leelaz
├── LICENSE
├── make.bat
├── Makefile
├── network.gz
├── problems
│   ├── alphago
│   └── alphago-2016
├── README.md
├── Release
│   └── data
├── res
│   ├── screen06_s.png
│   ├── sgoban.ico
│   ├── stone_distance.nb
│   └── stone_shape.nb
└── src
    ├── Board.cpp
    ├── Board.h
    ├── Camera.cpp
    ├── Camera.h
    ├── Complex.cpp
    ├── Complex.h
    ├── ElementGame.cpp
    ├── ElementGame.h
    ├── Event.cpp
    ├── Event.h
    ├── EventHandler.cpp
    ├── EventHandler.h
    ├── EventHandlerNewGame.cpp
    ├── EventHandlerNewGame.h
    ├── EventInstancer.cpp
    ├── EventInstancer.h
    ├── EventManager.cpp
    ├── EventManager.h
    ├── GameState.cpp
    ├── GameState.h
    ├── GameThread.cpp
    ├── GameThread.h
    ├── glyphy
    ├── GobanControl.cpp
    ├── GobanControl.h
    ├── GobanModel.cpp
    ├── GobanModel.h
    ├── GobanOverlay.cpp
    ├── GobanOverlay.h
    ├── GobanShader.cpp
    ├── GobanShader.h
    ├── GobanView.cpp
    ├── GobanView.h
    ├── gtpclient.cpp
    ├── gtpclient.h
    ├── main.cpp
    ├── Metrics.cpp
    ├── Metrics.h
    ├── opengl.h
    ├── player.cpp
    ├── player.h
    ├── Quaternion.cpp
    ├── Quaternion.h
    ├── sgf
    ├── shell
    ├── Vector.cpp
    └── Vector.h

**Comment by popojan** [comment]
I see, leelaz is in the project dir root, I guess the config should look like this:
> ./
> leelaz
> -g --quiet -t 2 -w ./network.gz --noponder
> leela_zero
> 0

**Comment by startnoob** [comment]
the same crash log file.

> setting komi 6.5
[2018-12-14 18:21:45.373] [console] [info] sendline = [komi 6.5]
[2018-12-14 18:21:45.373] [console] [info] get line
[2018-12-14 18:21:45.373] [console] [info] getline = [=]
[2018-12-14 18:21:45.373] [console] [info] getline = []
(core dumped)

Maybe there is something wrong with the code about the gtp connection or the komi changes.

**Comment by popojan** [comment]
is there gnugo installed and in the path?
have not you deleted main.txt config file?
i do not see loading gnugo engine in the logs
gnugo is neccessary as the main engine supervisor
i tried to reproduce the bug and it seems it is the case

**Comment by startnoob** [comment]
Thanks a lot! It works!
I advise you to add this tip to the readme file.

**Comment by startnoob** [comment]
@

**Comment by popojan** [comment]
You are welcome!
You are right, yes, the whole documentation/error handling/logging must be (re)worked.
