### ISSUE TITLE
Configurable komi

### ISSUE THREAD

**Issue by popojan** [popojan/goban#17]
Quick fix needed while waiting for GUI redesign
Based on lightvector/katago#224.

**Comment by lj739** [comment]
Version 24. 2. 2019 can't undo, version 13. 12. 2018 is ok.

**Comment by popojan** [comment]
> Version 24. 2. 2019 can't undo, version 13. 12. 2018 is ok.

Thanks for reporting, see issue #18.

In the meantime, please try private build [hraj.si/goban/goban_2020-05-15_lj739.zip](https://hraj.si/goban/goban_2020-05-15_lj739.zip). You can choose komi from drop down list defined in `data/gui/goban.rml`. (Got some difficulties styling text input field in rocketLib). Switching engines is now done using drop down lists as well.

The build is not thoroughly tested, subsequent bug reports are welcome :)

**Comment by lj739** [comment]
Great job. But undo function still not working. When I was playing as black, pressing u key to undo a move, a&nbsp; black stone and a white stone withdrawn, now it should be the turn of black, but white player took a move instead, and the white engine became abnormal after it usurped this step.

**Comment by popojan** [comment]
> But undo function still not working.

Meant to do it later, sorry. Fixed now, I hope.
Published a tiny update at [hraj.si/goban](https://hraj.si/goban) website.

**Comment by lj739** [comment]
fixed. many thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jan Popelka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 晚上7:59
收件人:&nbsp;"popojan/goban"<goban@noreply.github.com&gt;;
抄送:&nbsp;"费而隐"<909417887@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [popojan/goban] Configurable komi (#17)





  
But undo function still not working.
  
Meant to do it later, sorry. Fixed now, I hope.
 Published a tiny update at hraj.si/goban website.

**Comment by popojan** [comment]
You are welcome!
Please edit `data/gui/goban.rml` to include your favorite komis.
One day you will be able to type the value directly in the GUI.
