### ISSUE TITLE
Board not cleared in katago engine

### ISSUE THREAD

**Issue by popojan** [popojan/goban#19]
It gets confused when starting new game.

GTP docs on `boardsize` command: 
>Set the board size to NxN and clear the board.

In katago, board does not get cleared if size is set to same value as before.
We shall explicitly call `clear_board` when starting new game.

**Comment by lj739** [comment]
It is not a important issue, one can close goban and reload it . A important issue is,  you load a second engine to play against the primary engine, play some steps, and close it, when you load it again, the second engine becomes very weak, even playing some weird moves. If you choose the primary  engine as the second engine, let it play against itself , the second player can be changed to human or engine again and again, and the situation menitoned above will never happen.

**Comment by lj739** [comment]
It is not a important issue, one can close goban and reload it . A important issue is, you load a second engine to play against the primary engine, play some steps, and change it to human, when you reload it (from human back to engine), the second engine becomes very weak, even playing some weird moves. If you choose the primary engine as the second engine, let it play against itself , the second player can be changed to human or engine again and again, and the situation menitoned above will never happen.
