### ISSUE TITLE
Interface not working on my Windows 10 pc

### ISSUE THREAD

**Issue by gebeleizis** [popojan/goban#22]
I've been trying to run the app, but what I'm getting is this:
![goban 2020-05-20 10-23-18-11](https://user-images.githubusercontent.com/1134353/82417466-40b22a00-9a84-11ea-93c8-1dd1b5c16a53.jpg)
Any help would be greatly appreciated! Thank you very much in advance!

**Comment by popojan** [comment]
Looks familiar, please see #4, and then let's have a look on your graphics card specs.

**Comment by gebeleizis** [comment]
I checked the post and the fix with the graphic card. Unfortunately, I can't find out in what file  is the default card set. My laptop uses an Intel HD Graphics 520 card.

**Comment by popojan** [comment]
Well, it might even be the only graphics card in your laptop.
Good opportunity to find out what is wrong with the shader on some integrated cards.

Please try:
* switching to other shaders using V key (is the flat one with gray background also distorted?)
* look for error message in the black background window when goban starts
* run dxdiag and save the report, attach it if you don't mind 
* report of opengl capabilities would be most helpful, if you didn't mind installing a tool like https://www.realtech-vr.com/home/glview

**Comment by popojan** [comment]
Please substitute `data/glsl/fragment.glsl` with this file: [fragment.glsl.txt](https://github.com/popojan/goban/files/4656253/fragment.glsl.txt) (remove the `.txt` extension) and let me know, if anything changed. Thank you.

**Comment by gebeleizis** [comment]
No error messages on background except 2 warnings related to the sound (but the sound works OK). The dxdiag got me the parameters below:
![Capture](https://user-images.githubusercontent.com/1134353/82437924-e83d5580-9aa0-11ea-8153-8deb22ebdff8.JPG)
Changing the fragment.glsl file didn't make any difference. I also find curious that an app this small takes a dozen seconds or more to start on my pc. 
The result ov pressing the V key:
![goban 2020-05-20 13-54-57-94](https://user-images.githubusercontent.com/1134353/82438351-947f3c00-9aa1-11ea-989a-7be376d2c980.jpg)
![goban 2020-05-20 13-54-45-77](https://user-images.githubusercontent.com/1134353/82438359-977a2c80-9aa1-11ea-8353-66f9e58eb784.jpg)
I really appreciate all your help. Please take your time to reply, it's not urgent. I'm puzzled myself about the app behavior, as I've never had such issues with any software on this pc.

**Comment by popojan** [comment]
OK. Thank you for your patience. The long start is caused by slow compilation of the huge single-file shader (not a good practice by it was my design choice to implement all the geometry there), Subsequent starts should be faster, as your card should cache the compiled fragment shader code (until you change it). I will prepare several other versions of the shader and politely ask you to try them one by one to narrow down the issue.

Have you tried placing stone on such broken board? Please do.

**Comment by gebeleizis** [comment]
Placing stones works fine. I can also hear the sound. However, they look like this ^_^: 
![goban 2020-05-20 14-13-33-64](https://user-images.githubusercontent.com/1134353/82439904-20926300-9aa4-11ea-994b-5816451c84ad.jpg)

**Comment by popojan** [comment]
Thank you, that is another clue for me :-)

**Comment by popojan** [comment]
One more thing to try before I delve deep into the shader mess. Please replace `precision lowp float;` by `precision highp float;` in both `data/glsl/fragment.glsl` and `data/glsl/vertex.glsl`. It sits on second line in either file. (Be careful if editing in notepad, it must not add .txt extension). Thank you.

**Comment by gebeleizis** [comment]
Amazing! It worked like a charm! Thank you very, very much! You've made a great piece of software for the lovers of GO!

**Comment by popojan** [comment]
Thank you! I am glad it helped.

I will increase the default precision in the next release. It is easier than making the code numerically robust :)

Please do not hesitate to report other bugs or glitches, the software is in early stage of development - considering features and quality of the code base, not time it's been in existence.
