### ISSUE TITLE
when the sgf function could be added?

### ISSUE THREAD

**Issue by alphaladder** [popojan/goban#28]
Goban is a amazing phenomenon and we like it. However, there is no any 'save' function available in current version, and when will this be added ?

thanks

**Comment by popojan** [comment]
Thank you for your kind words. There is not, just the menu item. However, SGF export, followed by SGF import, are top priority now. To enable full SGF support I am looking for a good SGF library. I might give a try to [herzbube/libsgfcplusplus](/herzbube/libsgfcplusplus). If it is too difficult, I will do minimalistic SGF export by myself first. That could be done in a week or two.

**Comment by alphaladder** [comment]
Thank you for your quick response. Great pleasure.

**Comment by popojan** [comment]
Working on the export feature.
Using [GoWrite2](https://gowrite.net/GOWrite2.html) to view the exported files.
