### ISSUE TITLE
how to add another engine?

### ISSUE THREAD

**Issue by l1t1** [popojan/goban#3]
for example, leelazero

**Comment by l1t1** [comment]
I add leelaz files at /engine/leelaz and a config file  as following to engines.available and engines.enabled, it doesnt work correctly

./engine/leelaz
leelaz
leelaz  --gtp -w 12b-leelaz-model-swa-16-11100000.txt.gz
leelaz
0

**Comment by popojan** [comment]
in the meantime got it to work in wine with
```
./engine/leelaz
leelaz.exe
leelaz.exe --quiet --gtp -w ./engine/leelaz/best-network
leelaz
0
```
paths are meant to be relative to game root dir

**Comment by l1t1** [comment]
it works, thanks

**Comment by l1t1** [comment]
one more question, when i exit the goban, leelaz resports an error in a window.

**Comment by popojan** [comment]
The syntax for adding a new engine is as follows:
```
<directory with engine executable, possibly relative to working dir, empty if engine is in path>
<engine executable filename>
<engine executable with all command line parameters>
<name to be displayed in the gui>
<0 for any extra engine, 1 for main gnugo coach>
```
The file is to be placed in `config/engines.enabled`;  `config/engines.available` is just a storage for disabled engines. Engine management will likely change in the future.

Errors on exit might be caused by improper process termination. I will check it.

**Comment by popojan** [comment]
Slight change in syntax in [windows 10 builds](https://hraj.si/goban/) (switched to new integrated boost.process):
```
<directory with engine executable, possibly relative to working dir, or empty if in path>
<engine executable filename>
<*just* command line parameters>
<name to be displayed in the gui>
<0 for any extra engine, 1 for main gnugo coach>
```

**Comment by popojan** [comment]
Documented in the project's wiki.
