### ISSUE TITLE
Have you made some progress?

### ISSUE THREAD

**Issue by lj739** [popojan/goban#32]
Waiting for the new version.......

**Comment by popojan** [comment]
OK, nice to hear. Libsgfc++ integration is done, just bit more work needed to allow proper export of SGF record but I was busy doing other things.

**Comment by popojan** [comment]
While the answer is still NO, I am going to refactor shaders and implement all the other minor feature requests mentioned in the open issues, soon. So far, there is just a branch referencing #35 with (hopefully) somewhat improved textures.
