### ISSUE TITLE
Would you consider porting this to Unreal Engine 4.x? 

### ISSUE THREAD

**Issue by AscendChina** [popojan/goban#34]
Hi, Unreal Engine (the world most popular gaming/3D real time engine) uses C++ too... 
I have found much better graphics of Go set here: https://www.unrealengine.com/marketplace/en-US/product/go-set

Would you be able to help to integrate this into Unreal Engine and leverage the KataGo AI? I already asked the developer of the Go set and the KataGo developer and they are both okay with anyone using their stuff to create a goban 3D in Unreal Engine that is fully playable..

I have a "DF-41 Simulator" on Steam that has a goban in the underground command center of the nuclear missile sites, and wanted to make the Goban come to live and by fully intractable and playable rather than just a static mesh...

**Comment by popojan** [comment]
Hi hydrogenpi, thank you for an interesting link to a Go set model. However I do not consider porting, with my frequency of commits it would take forever to port it, or rather rewrite. By the way, when magnified, you see the model is a polygonal mesh. It could probably be circumvented by correctly using geometry / tessellation shaders, something I have no expertise in. So for the time being I will sticks with _all-code-in-the-fragment-shader_ design. What could be improved are the procedural textures, one could use normal mapping to fake bumpy/3D look, or even reflections etc. Graphic cards are constantly getting faster and comprise more shader units.
