### ISSUE TITLE
how to run this program in mac ox?

### ISSUE THREAD

**Issue by Akanezero** [popojan/goban#36]

**Comment by popojan** [comment]
While goban does not support building for Mac OS, there might be a way to run it.

Options to try:
* running windows build in [Wine](https://wiki.winehq.org/MacOS) (_Wine won't work on macOS Catalina 10.15_ though)
* running linux build from sources in a virtual machine, e.g. Oracle VM VirtualBox running Ubuntu

The latter option being quite impractical.

**Comment by popojan** [comment]
Shall we consider a rewrite in Rust?
There is an excellent cross-platform game engine [bevy](https://github.com/bevyengine/bevy).
There seems to be a stable [sgf-parse](https://github.com/julianandrews/sgf-parse) library.
Shaders could be more or less reused.
Time will tell.
