### ISSUE TITLE
Seem graphic broken in my computer

### ISSUE THREAD

**Issue by pangafu** [popojan/goban#4]
![goban](https://user-images.githubusercontent.com/10149168/49123787-e30ca980-f2f4-11e8-8079-aa455f412320.png)

My computer: 1050 notebook(xps) + 391.35 drivers

**Comment by pangafu** [comment]
update to driver 417.01, image still broken

**Comment by pangafu** [comment]
I found probem.. the default graphic card program use is 0, but my graphic card 0 is intel card.
I change the default graphic card to nvidia 1050, the problem solved!

**Comment by popojan** [comment]
strange artifacts, the shader should work even on integrated intel graphics
as long as `#version 300 es` shader language profile is supported
shall we trace the problem?

**Comment by popojan** [comment]
Quick workaround is to increase fragment and vertex shader float precision to:
`precision highp float;` See #22.
