### ISSUE TITLE
How to move the camera?

### ISSUE THREAD

**Issue by noword** [popojan/goban#40]
Thanks for your great working.

Right press the mouse, I can rotate; scroll the mouse, I can zoom.
How can I change the camera postion more freedom?

Actually, I try to make a program to recognize the SGF from Image.
I need more data to train/test the model.
I will open its source, when it almost done.

![1](https://user-images.githubusercontent.com/2698959/159402375-9d25d607-6750-4009-9789-6cf1d19e8fb7.jpg)

**Comment by popojan** [comment]
Hi noword,

you can drag the camera while either pressing the middle mouse button or the **d** key.
As for the zoom more precision is gained by moving mouse while pressing the **s** key.

I have not thought of such fancy use as generating training data for image recognition!
Maybe you could further profit from changing gamma and contrast (arrow keys) or altering [materials in the shader](https://github.com/popojan/goban/blob/f8abc753c6f4af33f963b781177a94757a5c6e17/data/shaders/legacy/fragment.glsl#L138).

Wish you a good luck with your project.
The screenshot preview looks promising.

**Comment by noword** [comment]
Thanks for your replay.
Shader/glsl is a new technology tree for me.
Hopefully I can find the transition matrix for the board, get the boxes of 4 corners.

**Comment by noword** [comment]
I opened its source.

https://github.com/noword/image2sgf
